language: go
sudo: required
dist: bionic

go:
  - 1.x
env:
- GO111MODULE=on
addons:
  apt:
    packages:
      - ipset
      - wireguard
script:
  - make ci

notifications:
  email:
    on_success: never
    on_failure: never
